#Deploy mysql-master and mysql-slave pods with automatic replication setup.
#Use Kubernetes ConfigMaps and Secrets for credentials.
#Ensure replication is configured on first launch.

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ABcdEF=  # Base64 for "password"
